### ISSUE TITLE
I'm not sure if this is a runtime error

### ISSUE THREAD

**Issue by ysh000112** [cenguix/Text2KGBench#15]
In the code line ‘python run_eval.py --eval_config_path config/tekgen_vicuna_config.json’, when I replace the configuration file, not all 7 configuration files in the config directory can run. Specifically, tikgen_alpaca_config.json and tikgen_vicuna_config.json both cannot run and show the following error:

Traceback (most recent call last):
  File "/home/wxy/ysh/Text2KGBench/Text2KGBench/src/evaluation/run_eval.py", line 355, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wxy/ysh/Text2KGBench/Text2KGBench/src/evaluation/run_eval.py", line 241, in main
    system_output = convert_to_dict(read_jsonl(onto['sys']))
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/ysh/Text2KGBench/Text2KGBench/src/evaluation/run_eval.py", line 141, in read_jsonl
    with open(jsonl_path) as in_file:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../data/baselines/alpaca-lora_13B/llm_responses/ont_1_movie_lora-13b_responses_v2.jsonl'

Traceback (most recent call last):
  File "/home/wxy/ysh/Text2KGBench/Text2KGBench/src/evaluation/run_eval.py", line 355, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wxy/ysh/Text2KGBench/Text2KGBench/src/evaluation/run_eval.py", line 241, in main
    system_output = convert_to_dict(read_jsonl(onto['sys']))
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/ysh/Text2KGBench/Text2KGBench/src/evaluation/run_eval.py", line 141, in read_jsonl
    with open(jsonl_path) as in_file:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../data/baselines/vicuna_13B/llm_responses/ont_1_movie_llm_responses.jsonl'

**Comment by jiangsufirstlove** [comment]
Can you write a README for the entire project on how to run it? Because your paper does not cover the training process. I'd like to validate the capabilities of Text2KGBench.If possible, I would greatly appreciate it.

**Comment by jiangsufirstlove** [comment]
Cound you write a README for the entire project on how to run it? Because your paper does not cover the training process. I'd like to validate the capabilities of Text2KGBench.If possible, I would greatly appreciate it.

**Comment by nandana** [comment]
This seems to be a relative path resolution error. Were you able to resolve this?
